### PR TITLE
initial database/table created

### PR DESCRIPTION
**Pull request by spenceryork**
# Description

Initial database and tables created.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

In order to test this run the following commands
```
$ npm install
```
(This will install the necessary packages.)

- Next run:
```
node db/build_table.js
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by spenceryork** [comment]
I updated the column in the `Customer` table to include phone number. I just replaced account_creation_date. Didn't seem needed.

**Review by sladeutley — APPROVED** [review]
👍

**Review by CourtneyBrothers — APPROVED** [review]
🗡  nice work! 🤜 🤛

**Review by sarahmorrisokeefe — APPROVED** [review]
🎨

**Review by EliOJackson — APPROVED** [review]
@spenceryork 🌵

**Pull request merged**
