### PR TITLE
User is able to add payment option for a customer

### LINKED ISSUE #3: User should be able to add a payment option for a customer
**Given** a customer has been made active in the program
**When** the user selects the option to add a payment type
**Then** the user should be prompted to enter in all appropriate information for a payment type
**And** when complete, the payment type should be added for the active customer

```bash
Enter payment type (e.g. AmEx, Visa, Checking)
>

Enter account number
>
```

### PR DESCRIPTION
**Pull request by sladeutley**
# Description

When an active customer is selected, the user is is able to then add a payment option for that customer.

Fixes #3 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

In terminal, run
```node db/build_table.js```

Make sure all tests are passing
```npm test```

There should be 9 tests passing for payment types.

Run ```npm start``` to ensure the option to add payment types for a customer is functioning with CLI
- select option 2 to activate a customer
- select option 3 to add payment type for that customer
- follow the prompts to enter payment type and account number
- check the table in db browser to see if the payment option has been added for that customer

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by CourtneyBrothers — COMMENTED** [review]
looks good please update pull request to remove reference to account type prompt

**Comment by sarahmorrisokeefe** [comment]
Miiiiight want to change the console log when you try to add a payment type before selecting an active customer. Up to you.

**Review by sarahmorrisokeefe — APPROVED** [review]
👍

**Comment by CourtneyBrothers** [comment]
thanks! 👍

**Comment by sladeutley** [comment]
made those changes! @CourtneyBrothers

**Review by CourtneyBrothers — APPROVED** [review]
🥇

**Pull request merged**
