### PR TITLE
Ability to Choose Active customer from Prompt

### PR DESCRIPTION
**Pull request by spenceryork**
# Description

This pull request completes all requirements for issue #2. Users are now able to choose an active customer from the command line. We also introduced a test for the getAll customers function.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

To test the command line run the following commands:
```
npm start
```
- Select number 2 from the command line.
- You should see a list of all customers.
- Enter a customer ID number and hit enter.
- After selecting a customer you should be directed back to the initial Welcome prompt. There will be a message within the prompt that indicates which customer is now listed as your active customer.

**RUNNING TESTS**

To initiate the testing run the following command:
```
npm test
```
- There should be 8 test that pass.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by CourtneyBrothers — APPROVED** [review]
👊 noice!

**Review by sarahmorrisokeefe — APPROVED** [review]
🍏

**Review by sarahmorrisokeefe — CHANGES_REQUESTED** [review]
Hey this looks awesome - but found something. I think we need to run a check on the database to check if the customer ID that the user puts in actually exists. We can talk about how we want to go about that in a second.

**Review by EliOJackson — CHANGES_REQUESTED** [review]
Hey Spencer, when I input a number that does not exist, it still sets that customer ID as the active ID. Can we have a check to see if that ID exists in the DB first?

**Comment by spenceryork** [comment]
@EliOJackson @sarahmorris926 - changes have been made to address the situation. New code has been pushed up.

**Review by EliOJackson — APPROVED** [review]

**Review by sarahmorrisokeefe — APPROVED** [review]
Looks good

**Pull request merged**
