### PR TITLE
Cb issue6 additional testing

### LINKED ISSUE #6: User should be able to able to complete a customer order
**Given** a customer has been made active in the program
**When** the user selects the option to complete an order
**Then** the user should be prompted to choose one of the active customer's payment options
**And** when one is chosen, the payment option should be added to the open order

If no products have been selected yet

```bash
Please add some products to your order first. Press any key to return to main menu.
```

If there are current products in an order

```bash
Your order total is $149.54. Ready to purchase
(Y/N) >

# If user entered Y
Choose a payment option
1. Amex
2. Visa
>

### PR DESCRIPTION
**Pull request by CourtneyBrothers**
# Description

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes #6 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

1. run node db/build_table to generate database
2. npm test to run test suite in the order 
```
node db/build_table.js
npm test test/order.test.js
npm test test/paymentType.test.js
npm test test/product.test.js
npm test test/order_product.test.js
npm test test/customer.test.js

```

3. npm start to run CLI
    1. select active customer 
    2. enter 6 on the command line to complete an order
    3. CLI will prompt with current order total, enter Y or N
        1. if N CLI will exit with console log (‘You chose to not complete your order!’)
    4.  If Y CLI will prompt to chose a payment option, enter the number of the payment option that is chosen
    5. Console will log payment completed, run npm test or refresh the database to view successful update 

# Checklist:

- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
unit test for 1) post one order product should return the object posted when called by the Line ID DOES NOT PASS LOCALLY 
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by EliOJackson — APPROVED** [review]
seems pretty good dude

**Review by sarahmorrisokeefe — APPROVED** [review]
Looks great! 💯 #sendit

**Review by sladeutley — APPROVED** [review]
Really good, just get the quantity from the product_orders table for open orders

**Comment by CourtneyBrothers** [comment]
@sladeutley good catch !

**Pull request merged**
