### PR TITLE
Adding a product to sell

### LINKED ISSUE #4: User should be able to add a product for a customer
**Given** a customer has been made active in the program
**When** the user selects the option to add a product
**Then** the user should be prompted to enter in all appropriate information for a product
**And** when complete, the product should be added for the active customer

### PR DESCRIPTION
**Pull request by sarahmorrisokeefe**
# Description

This pull request allows the user to add a product to sell once they have selected the correct active customer. 

Fixes #4 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

First, you will need to install any/all dependencies used in this sprint:
```
npm install
```
Next, you should run the tests. I have found that there is one test that sometimes fails, depending on when you last ran the tests. If it fails, you can usually fix it by quitting the test suite and running the command again: 
```
npm test
```
There should be 16 tests passing (not including outside pull requests or other user content).

Once you get the dependencies installed/updated and the tests passing, you can use the CLI. The user should be able to type `npm start` and see the prompt CLI. 
- The user will need to select an active customer (option number 2) before he or she can add a product. If the user tries to add a product (option number 4) before selecting a customer, it will throw an error and put the user back into the main menu. 
- Once the user selects an active customer, he or she will choose option 4 and start inputting the data needed for a new product. If the user tries to put a word in for the quantity or price, it will throw an error and tell the user to put in a number. 
- After the user completes the process of adding a product, it will console log `Product has been added: ${product_name}` and put the user back in the main menu.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sarahmorrisokeefe** [comment]
Please ignore until I fix merge conflicts from last branch! Thanks!

**Comment by sarahmorrisokeefe** [comment]
@EliOJackson @spenceryork @CourtneyBrothers @sladeutley fixed merge conflicts - ready for review now! Let me know what issues come up.

**Review by spenceryork — APPROVED** [review]
✈️ looks good!

**Review by sladeutley — APPROVED** [review]
👍

**Review by CourtneyBrothers — APPROVED** [review]
great job! 926!

**Pull request merged**
